[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "musep"
version = "0.1.0"
description = "Music Source Separation Toolkit"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Joris Vaneyghen", email = "joris.vaneyghen@gmail.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
keywords = ["audio", "source-separation", "deep-learning", "pytorch"]
requires-python = ">=3.9"
dependencies = [
    "torch",
    "torchaudio",
    "numpy",
    "librosa",
    "soundfile",
    "hydra-core",
    "torchaudio",
    "torchinfo",
    "torchview",
    "tqdm",
    "wandb",
    "audiomentations",
    "einops",
]

[project.optional-dependencies]
data = ["pandas", "tqdm", "scipy"]
#train = [
#    "wandb",
#    "tensorboard",
#    "torch-tb-profiler",
#    "torch-xla>=2.0.0",
#    "fairscale",
#]
#inference = ["onnx", "onnxruntime", "onnx-simplifier"]
#dev = ["pytest", "black", "isort", "mypy", "flake8", "pre-commit"]

[project.urls]
Homepage = "https://github.com/joris-vaneyghen/musep"
Repository = "https://github.com/joris-vaneyghen/musep"
Documentation = "https://github.com/joris-vaneyghen/musep"

[project.scripts]
musep-dataset-info = "musep.cli.dataset_info:main"
musep-model-info = "musep.cli.model_info:main"
musep-generate-mixes = "musep.cli.generate_mixes:main"
musep-train = "musep.cli.train:main"

[tool.setuptools.package-data]
musep = ["configs/*.yaml", "configs/**/*.yaml"]

[tool.setuptools.packages.find]
where = ["src"]