defaults:
  - optimizer: adafactor
  #  - lr_scheduler: steplr
  - loss: l1
  - monitoring: default

device: cuda
stft_device: cuda
#lr_scheduler:
#  step_size: 10
#  gamma: 0.2
mus_sep_loss_domain: tf_domain
epochs: 10
batch_size: 4
checkpoint_interval: 10
checkpoint_dir: ./checkpoints
num_workers: 4
seed: 42
deterministic: true

