defaults:
  - random_mix: default

train:
  audio_file_csv:
    - /kaggle/input/notebooks/jorisvaneyghen/musdb18hq-csv/train.csv
  predefined_jsonl_path: ${oc.env:PWD}/train

validation:
  audio_file_csv:
    - /kaggle/input/notebooks/jorisvaneyghen/musdb18hq-csv/validation.csv
  predefined_jsonl_path: ${oc.env:PWD}/validation.jsonl

sample_rate: ${model.sample_rate}
segment_length: ${model.segment_length}
channels: ${model.channels}

target_sources:
  drums:
    - drums
  bass:
    - bass
  vocals:
    - vocals
  other:
    - other

random_mix:
  mix_strategy: fixed_number
  fixed_number_of_mixes: 3200